// Code generated by "stringer -type=FunType"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FFun-0]
	_ = x[FInit-1]
	_ = x[FMethod-2]
	_ = x[FScript-3]
}

const _FunType_name = "FFunFInitFMethodFScript"

var _FunType_index = [...]uint8{0, 4, 9, 16, 23}

func (i FunType) String() string {
	if i < 0 || i >= FunType(len(_FunType_index)-1) {
		return "FunType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FunType_name[_FunType_index[i]:_FunType_index[i+1]]
}
