// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpReturn-0]
	_ = x[OpConst-1]
	_ = x[OpNil-2]
	_ = x[OpTrue-3]
	_ = x[OpFalse-4]
	_ = x[OpPop-5]
	_ = x[OpGetLocal-6]
	_ = x[OpSetLocal-7]
	_ = x[OpGetGlobal-8]
	_ = x[OpDefGlobal-9]
	_ = x[OpSetGlobal-10]
	_ = x[OpGetUpval-11]
	_ = x[OpSetUpval-12]
	_ = x[OpEqual-13]
	_ = x[OpGreater-14]
	_ = x[OpLess-15]
	_ = x[OpNot-16]
	_ = x[OpNeg-17]
	_ = x[OpAdd-18]
	_ = x[OpSub-19]
	_ = x[OpMul-20]
	_ = x[OpDiv-21]
	_ = x[OpPrint-22]
	_ = x[OpJump-23]
	_ = x[OpJumpUnless-24]
	_ = x[OpLoop-25]
	_ = x[OpCall-26]
	_ = x[OpClos-27]
}

const _OpCode_name = "OpReturnOpConstOpNilOpTrueOpFalseOpPopOpGetLocalOpSetLocalOpGetGlobalOpDefGlobalOpSetGlobalOpGetUpvalOpSetUpvalOpEqualOpGreaterOpLessOpNotOpNegOpAddOpSubOpMulOpDivOpPrintOpJumpOpJumpUnlessOpLoopOpCallOpClos"

var _OpCode_index = [...]uint8{0, 8, 15, 20, 26, 33, 38, 48, 58, 69, 80, 91, 101, 111, 118, 127, 133, 138, 143, 148, 153, 158, 163, 170, 176, 188, 194, 200, 206}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
