// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TLParen-0]
	_ = x[TRParen-1]
	_ = x[TLBrace-2]
	_ = x[TRBrace-3]
	_ = x[TComma-4]
	_ = x[TDot-5]
	_ = x[TMinus-6]
	_ = x[TPlus-7]
	_ = x[TSemi-8]
	_ = x[TSlash-9]
	_ = x[TStar-10]
	_ = x[TBang-11]
	_ = x[TBangEqual-12]
	_ = x[TEqual-13]
	_ = x[TEqualEqual-14]
	_ = x[TGreater-15]
	_ = x[TGreaterEqual-16]
	_ = x[TLess-17]
	_ = x[TLessEqual-18]
	_ = x[TIdent-19]
	_ = x[TStr-20]
	_ = x[TNum-21]
	_ = x[TAnd-22]
	_ = x[TBreak-23]
	_ = x[TClass-24]
	_ = x[TContinue-25]
	_ = x[TElse-26]
	_ = x[TFalse-27]
	_ = x[TFor-28]
	_ = x[TFun-29]
	_ = x[TIf-30]
	_ = x[TNil-31]
	_ = x[TOr-32]
	_ = x[TPrint-33]
	_ = x[TReturn-34]
	_ = x[TSuper-35]
	_ = x[TThis-36]
	_ = x[TTrue-37]
	_ = x[TVar-38]
	_ = x[TWhile-39]
	_ = x[TErr-40]
	_ = x[TEOF-41]
}

const _TokenType_name = "TLParenTRParenTLBraceTRBraceTCommaTDotTMinusTPlusTSemiTSlashTStarTBangTBangEqualTEqualTEqualEqualTGreaterTGreaterEqualTLessTLessEqualTIdentTStrTNumTAndTBreakTClassTContinueTElseTFalseTForTFunTIfTNilTOrTPrintTReturnTSuperTThisTTrueTVarTWhileTErrTEOF"

var _TokenType_index = [...]uint8{0, 7, 14, 21, 28, 34, 38, 44, 49, 54, 60, 65, 70, 80, 86, 97, 105, 118, 123, 133, 139, 143, 147, 151, 157, 163, 172, 177, 183, 187, 191, 194, 198, 201, 207, 214, 220, 225, 230, 234, 240, 244, 248}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
